global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'
  group_by: ['alertname','job','instance']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 3h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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" # Slack Webhook URL
        channel: '#모니터링'
        send_resolved: true

#alertmanager.yml 안에서 환경변수 치환 기능을 지원하지 않는다 -> env X

