version: "3.9"
networks:
  monitoring_net:
    external: true

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus-data:/prometheus
    networks: [monitoring_net]

  alertmanager:
    image: prom/alertmanager:v0.28.1
    restart: always
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
      - ./alertmanager/secrets:/etc/alertmanager/secrets:ro  
    networks: [monitoring_net]

  grafana:
    image: grafana/grafana:10.4.5
    restart: always
    env_file:
      - drf_api/.env 
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SERVER_ROOT_URL=https://grafana.5range.site
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks: [monitoring_net]
    ports:
      - "127.0.0.1:3000:3000"

