version: "3.9"

services:
  app:
    build:
      context: ./drf_api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - drf_api/.env   # 여기서 전부 읽어옴
    volumes:
      - static-data:/vol/web 
    environment:
      - DJANGO_SETTINGS_MODULE=drf_api.settings   # 고정값만 남김
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
        - drf_api/.env   # DB_NAME, DB_USER, DB_PASS 그대로 사용

volumes:
  postgres-data:
  static-data:
