version: "3.9"

services:
  app:
    build:
      context: ./drf_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - drf_api/.env
    volumes:
      - /home/ec2-user/sign_language_video_call/static:/vol/web/static
      - /home/ec2-user/sign_language_video_call/media:/vol/web/media
    environment:
      - DJANGO_SETTINGS_MODULE=drf_api.settings # 고정값만 남김
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

    env_file:
      - drf_api/.env # DB_NAME, DB_USER, DB_PASS 그대로 사용

volumes:
  postgres-data:
  static-data:
