version: "3.9"

services:
  app:
    build:
      context: ./drf_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    # 컨테이너 시작 시 자동으로 읽음(비밀번호, API키 등)
    env_file:
      - drf_api/.env
    # 런타임 환경변수로 바로 주입, 단일 또는 고정 값 설정에 편리(DJANGO_SETTINGS_MODULE 등)
    environment:
      - DJANGO_SETTINGS_MODULE=drf_api.settings
      - ENV=production
    volumes:
      - /home/ec2-user/sign_language_video_call/static:/vol/web/static
      - /home/ec2-user/sign_language_video_call/media:/vol/web/media

    depends_on:
      - db

    networks: #promethus가 접근할 수 있도록 공용 네트워크
      - default
      - monitoring_net

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

    env_file:
      - drf_api/.env

    networks: #db metric을 가져올 거라면 필요 (필수 X)
      - default

volumes:
  postgres-data:
  static-data:

networks: #네트워크 블록 추가
  default:
  monitoring_net: #monitoring_net을 external 네크워크로 선언.
    external: true
