version: "3.9"

services:
  app:
    build:
      context: ./drf_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    # 컨테이너 시작 시 자동으로 읽음(비밀번호, API키 등)
    env_file:
      - drf_api/.env
    # 런타임 환경변수로 바로 주입, 단일 또는 고정 값 설정에 편리(DJANGO_SETTINGS_MODULE 등)
    environment:
      - DJANGO_SETTINGS_MODULE=drf_api.settings
    volumes:
      - /home/ec2-user/sign_language_video_call/static:/vol/web/static
      - /home/ec2-user/sign_language_video_call/media:/vol/web/media

    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

    env_file:
      - drf_api/.env

volumes:
  postgres-data:
  static-data:
