version: "3.9"

services:
  app:
    build:
      context: ./drf_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    # 컨테이너 시작 시 자동으로 읽음(비밀번호, API키 등)
    env_file:
      - drf_api/.env
    # 런타임 환경변수로 바로 주입, 단일 또는 고정 값 설정에 편리(DJANGO_SETTINGS_MODULE 등)
    environment:
      - DJANGO_SETTINGS_MODULE=drf_api.settings
    volumes:
      - /home/ec2-user/sign_language_video_call/static:/vol/web/static
      - /home/ec2-user/sign_language_video_call/media:/vol/web/media

    depends_on:
      - db
      - redis

    networks: #promethus가 접근할 수 있도록 공용 네트워크
      - default
      - monitoring_net

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

    env_file:
      - drf_api/.env

    networks: #db metric을 가져올 거라면 필요 (필수 X)
      - default

  redis: # <- 추가
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default
  
  ai:
    build:
      context: ./fastapi_api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
  
    # 포트는 prod에서는 Nginx 통해서만 접근 → ports 생략


volumes:
  postgres-data:
  static-data:

networks: #네트워크 블록 추가
  default:
  monitoring_net: #monitoring_net을 external 네크워크로 선언.
    external: true
