# Generated by Django 5.1.11 on 2025-08-09 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('FRIEND_REQUEST', '친구 요청'), ('FRIEND_ACCEPTED', '친구 수락'), ('FRIEND_REJECTED', '친구 거절'), ('CALL_INCOMING', '전화 요청 옴'), ('CALL_REJECTED', '전화 거절됨'), ('CALL_MISSED', '부재중 전화'), ('CREDIT_LOW', '크레딧 부족'), ('SYSTEM', '시스템 안내')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
