# Generated by Django 5.1.12 on 2025-09-29 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
    ]
