# Generated by Django 5.1.12 on 2025-09-29 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credits",
            options={"verbose_name": "Credit", "verbose_name_plural": "Credits"},
        ),
    ]
