# Generated by Django 5.1.12 on 2025-09-29 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
            },
        ),
    ]
