# Generated by Django 5.1.11 on 2025-08-13 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendrelations",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="friendrelations",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("from_user", "to_user"),
                name="uniq_pending_per_direction",
            ),
        ),
    ]
