# Generated by Django 5.1.12 on 2025-09-23 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0004_remove_friendrelations_uniq_pending_any_direction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="friend",
            index=models.Index(
                fields=["-created_at"], name="friend_created_at_desc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="friendrelations",
            index=models.Index(
                fields=["to_user", "status", "-id"], name="friendreq_received_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="friendrelations",
            index=models.Index(
                fields=["from_user", "status", "-id"], name="friendreq_sent_idx"
            ),
        ),
    ]
