# Generated by Django 5.1.12 on 2025-09-26 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friend", "0005_friend_friend_created_at_desc_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="friend",
            name="friend_created_at_desc_idx",
        ),
        migrations.RemoveIndex(
            model_name="friendrelations",
            name="friendreq_received_idx",
        ),
        migrations.RemoveIndex(
            model_name="friendrelations",
            name="friendreq_sent_idx",
        ),
    ]
