# Generated by Django 5.1.11 on 2025-08-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callhistory',
            old_name='created_at',
            new_name='called_at',
        ),
    ]
