# Generated by Django 5.1.11 on 2025-08-15 08:07

import uuid

from django.db import migrations, models


def gen():
    return uuid.uuid4().hex[:22]

def fill_room_id(apps, schema_editor):
    CallHistory = apps.get_model('call', 'CallHistory')
    used = set(CallHistory.objects.exclude(room_id__isnull=True)
               .values_list('room_id', flat=True))
    for obj in CallHistory.objects.filter(room_id__isnull=True).iterator():
        rid = gen()
        while rid in used:
            rid = gen()
        obj.room_id = rid
        obj.save(update_fields=['room_id'])
        used.add(rid)

class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_rename_created_at_callhistory_called_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='room_id',
            field=models.CharField(max_length=22, null=True, blank=True),
        ),
        migrations.RunPython(fill_room_id, migrations.RunPython.noop),  # ← 이 줄 필수
    ]