# Generated by Django 5.1.11 on 2025-08-15 08:11

from django.db import migrations, models

import call.models


class Migration(migrations.Migration):
    dependencies = [
        ("call", "0003_callhistory_room_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callhistory",
            name="room_id",
            field=models.CharField(
                default=call.models.gen_room_id, max_length=22, unique=True
            ),
        ),
    ]
