# Generated by Django 5.1.11 on 2025-08-08 14:57

from django.db import migrations, models

import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.profile_image_file_path
            ),
        ),
    ]
