# Generated by Django 5.1.12 on 2025-09-29 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_profile_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
